In [6]:
animal_outcomes = load_data("../data/train.csv")
animal_outcomes.head()

,animal_id,name,date_time,outcome_type,outcome_subtype,animal_type,sex_upon_outcome,age_upon_outcome,breed,color
0,A671945,Hambone,2014-02-12 18:22:00,Return_to_owner,Unknown,Dog,Neutered Male,1 year,Shetland Sheepdog Mix,Brown/White
1,A656520,Emily,2013-10-13 12:44:00,Euthanasia,Suffering,Cat,Spayed Female,1 year,Domestic Shorthair Mix,Cream Tabby
2,A686464,Pearce,2015-01-31 12:28:00,Adoption,Foster,Dog,Neutered Male,2 years,Pit Bull Mix,Blue/White
3,A683430,Unknown,2014-07-11 19:09:00,Transfer,Partner,Cat,Intact Male,3 weeks,Domestic Shorthair Mix,Blue Cream
4,A667013,Unknown,2013-11-15 12:52:00,Transfer,Partner,Dog,Neutered Male,2 years,Lhasa Apso/Miniature Poodle,Tan

In [7]:
animal_outcomes = load_data("../data/train.csv")
with_features = add_features(animal_outcomes)
with_features.head()

,animal_id,name,date_time,outcome_type,outcome_subtype,animal_type,sex_upon_outcome,age_upon_outcome,breed,color,is_dog,has_name,sex,neutered,hair_type,days_upon_outcome
0,A671945,Hambone,2014-02-12 18:22:00,Return_to_owner,Unknown,Dog,Neutered Male,1 year,Shetland Sheepdog Mix,Brown/White,True,True,male,fixed,unknown,365.0
1,A656520,Emily,2013-10-13 12:44:00,Euthanasia,Suffering,Cat,Spayed Female,1 year,Domestic Shorthair Mix,Cream Tabby,False,True,female,fixed,shorthair,365.0
2,A686464,Pearce,2015-01-31 12:28:00,Adoption,Foster,Dog,Neutered Male,2 years,Pit Bull Mix,Blue/White,True,True,male,fixed,unknown,730.0
3,A683430,Unknown,2014-07-11 19:09:00,Transfer,Partner,Cat,Intact Male,3 weeks,Domestic Shorthair Mix,Blue Cream,False,False,male,intact,shorthair,21.0
4,A667013,Unknown,2013-11-15 12:52:00,Transfer,Partner,Dog,Neutered Male,2 years,Lhasa Apso/Miniature Poodle,Tan,True,False,male,fixed,unknown,730.0

In [8]:
from animal_shelter.data import load_data
from animal_shelter.features import add_features

animal_outcomes = load_data("../data/test.csv")
with_features = add_features(animal_outcomes)
with_features.head()

,id,name,date_time,animal_type,sex_upon_outcome,age_upon_outcome,breed,color,is_dog,has_name,sex,neutered,hair_type,days_upon_outcome
0,1,Summer,2015-10-12 12:15:00,Dog,Intact Female,10 months,Labrador Retriever Mix,Red/White,True,True,female,intact,unknown,300.0
1,2,Cheyenne,2014-07-26 17:59:00,Dog,Spayed Female,2 years,German Shepherd/Siberian Husky,Black/Tan,True,True,female,fixed,unknown,730.0
2,3,Gus,2016-01-13 12:20:00,Cat,Neutered Male,1 year,Domestic Shorthair Mix,Brown Tabby,False,True,male,fixed,shorthair,365.0
3,4,Pongo,2013-12-28 18:12:00,Dog,Intact Male,4 months,Collie Smooth Mix,Tricolor,True,True,male,intact,unknown,120.0
4,5,Skooter,2015-09-24 17:59:00,Dog,Neutered Male,2 years,Miniature Poodle Mix,White,True,True,male,fixed,unknown,730.0

In [12]:
from animal_shelter.data import load_data
from animal_shelter.features import add_features

animal_outcomes = load_data("../data/test.csv")
with_features = add_features(animal_outcomes)
with_features.head()

,id,name,date_time,animal_type,sex_upon_outcome,age_upon_outcome,breed,color,is_dog,has_name,sex,neutered,hair_type,days_upon_outcome
0,1,Summer,2015-10-12 12:15:00,Dog,Intact Female,10 months,Labrador Retriever Mix,Red/White,True,True,female,intact,unknown,300.0
1,2,Cheyenne,2014-07-26 17:59:00,Dog,Spayed Female,2 years,German Shepherd/Siberian Husky,Black/Tan,True,True,female,fixed,unknown,730.0
2,3,Gus,2016-01-13 12:20:00,Cat,Neutered Male,1 year,Domestic Shorthair Mix,Brown Tabby,False,True,male,fixed,shorthair,365.0
3,4,Pongo,2013-12-28 18:12:00,Dog,Intact Male,4 months,Collie Smooth Mix,Tricolor,True,True,male,intact,unknown,120.0
4,5,Skooter,2015-09-24 17:59:00,Dog,Neutered Male,2 years,Miniature Poodle Mix,White,True,True,male,fixed,unknown,730.0

In [13]:
%load_ext autoreload
%autoreload 2